# Site settings
title: Empirische Schul- und Unterrichtsforschung
subtitle: 
email: empschul@uni-leipzig.de
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://empschul-leipzig.github.io" # the base hostname & protocol for your site
author:
street_address: Dittrichring 5-7
city: 04109 Leipzig
state: Sachsen
zip_code: 
country: Deutschland
phone: +49 (0) 341 97-31570

# Social settings
github_url: https://github.com/empschul-leipzig
slack_url: https://empschul.slack.com
twitter_url: 

# Build settings
markdown: kramdown
