# Site settings
title: Empirische Schul- und Unterrichtsforschung
subtitle: 
email: empschul@uni-leipzig.de
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://empschul-leipzig.github.io" # the base hostname & protocol for your site
author:
street_address: Dittrichring 5-7
city: 04109 Leipzig
state: Sachsen
zip_code: 
country: Deutschland
phone: +49 (0) 341 97-31570

# Social settings
500px_url:
facebook_url:
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url: 
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
