# Site settings
title: Empirische Schul- und Unterrichtsforschung
subtitle: 
email: empschul@uni-leipzig.de
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://empschul-leipzig.github.io" # the base hostname & protocol for your site
author:
street_address: Marschnerstraße 29 a
city: Leipzig
state: 
zip_code: 04109
country: Deutschland
phone: +49 (0) 341 97-31570

# Social settings
github_url: https://github.com/empschul-leipzig
slack_url: https://empschul.slack.com
twitter_url: https://twitter.com/empschul 
university_url: https://www.erzwiss.uni-leipzig.de/institut-fuer-bildungswissenschaften/empirische-schul-und-unterrichtsforschung#c330830

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
